### PR TITLE
refactor(*): add placeholder test structure

### PR DESCRIPTION
**Pull request by jai**
### Info Required for All Commits

Description:

* Updates repo structure to allow testing

---
This change is [Reviewable](https://reviewable.io/reviews/honestbank/argoflow-aws-infrastructure/1)

### CODE REVIEW

**Review by pgcloud — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/honestbank/argoflow-aws-infrastructure/1)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @jai and @theerasan)

___
*[terraform/iam.tf, line 27 at r1](https://reviewable.io/reviews/honestbank/argoflow-aws-infrastructure/1#-MjYLijA5pVME_82DEMP:-MjYLijBCecLwrWUJspz:bnlggii) ([raw file](https://github.com/honestbank/argoflow-aws-infrastructure/blob/cd1945881193d2850b70e53f9affe31e4ef14b5d/terraform/iam.tf#L27)):*
> ```HCL
>   description = "IAM Policy allowing the AWS Load Balancer Controller to administer infrastructure resources"
> 
>   policy = file(".../iam-policies/aws-load-balancer-controller.json")
> ```

Too many dots

**Review by jai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/honestbank/argoflow-aws-infrastructure/1)* status: 9 of 12 files reviewed, 1 unresolved discussion (waiting on @pgcloud and @theerasan)

___
*[terraform/iam.tf, line 27 at r1](https://reviewable.io/reviews/honestbank/argoflow-aws-infrastructure/1#-MjYLijA5pVME_82DEMP:-Mjb6o9E14SlpfWaZ45C:bb7f2mf) ([raw file](https://github.com/honestbank/argoflow-aws-infrastructure/blob/cd1945881193d2850b70e53f9affe31e4ef14b5d/terraform/iam.tf#L27)):*
<details><summary><i>Previously, pgcloud wrote…</i></summary><blockquote>

Too many dots
</blockquote></details>

done

**Review by pgcloud — APPROVED** [review]
> Reviewed 1 of 11 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/honestbank/argoflow-aws-infrastructure/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @theerasan)

**Review by theerasan — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/honestbank/argoflow-aws-infrastructure/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jai)

**Pull request merged**
